name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.9' # specify the Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Build Web Application
      run: flutter build web --release
    
    - name: Make copy of artifacts
      run: |
        chmod u+x "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
        bash "${GITHUB_WORKSPACE}/createandcopytofolder.sh"

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Commit the artifacts.
